# FITS File — All Headers Explorer
Run this notebook on your JWST `.fits` file to see every header from every extension.

In [11]:
from astropy.io import fits
from pathlib import Path

original_path = Path(r"T:\JWST-Timing\MAST_2023-10-07T0548\JWST")

## Step 1 — Loop over all files and frames (fixed)
**Bug fixed:** `range(istart, iend+1)` → `range(istart, iend)` to avoid index out of bounds on the last frame.

In [12]:
for epoch in ["epoch1", "epoch2"]:
    for wave_type in ["lw", "sw"]:

        if epoch == "epoch1":
            sw_files = sorted(original_path.glob("jw01666001001*_nrcb1/*crfints.fits"))
            lw_files = sorted(original_path.glob("jw01666001001*_nrcblong/*crfints.fits"))
        else:
            sw_files = sorted(original_path.glob("jw01666003001*_nrcb1/*crfints.fits"))
            lw_files = sorted(original_path.glob("jw01666003001*_nrcblong/*crfints.fits"))

        fileList = lw_files if wave_type == "lw" else sw_files

        for filename in fileList:
            print(f"Processing {filename}...")

            with fits.open(filename) as f:
                data = f["SCI"]

                istart = 0
                iend = data.data.shape[0]  # total number of frames

                for i in range(istart, iend):
                    print(f"  File: {filename.name}   Frame: {i + 1} / {iend}")

Processing T:\JWST-Timing\MAST_2023-10-07T0548\JWST\jw01666001001_02102_00001-seg001_nrcblong\jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits...
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 1 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 2 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 3 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 4 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 5 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 6 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 7 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 8 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 9 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 10 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 11 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 12 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 13 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 14 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 15 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 16 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 17 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 18 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 19 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 20 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 21 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 22 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 23 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 24 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 25 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 26 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 27 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 28 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 29 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 30 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 31 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 32 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 33 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 34 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 35 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 36 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 37 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 38 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 39 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 40 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 41 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 42 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 43 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 44 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 45 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 46 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 47 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 48 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 49 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 50 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 51 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 52 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 53 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 54 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 55 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 56 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 57 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 58 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 59 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 60 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 61 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 62 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 63 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 64 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 65 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 66 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 67 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 68 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 69 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 70 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 71 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 72 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 73 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 74 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 75 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 76 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 77 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 78 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 79 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 80 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 81 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 82 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 83 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 84 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 85 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 86 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 87 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 88 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 89 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 90 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 91 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 92 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 93 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 94 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 95 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 96 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 97 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 98 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 99 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 100 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 101 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 102 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 103 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 104 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 105 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 106 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 107 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 108 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 109 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 110 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 111 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 112 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 113 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 114 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 115 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 116 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 117 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 118 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 119 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 120 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 121 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 122 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 123 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 124 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 125 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 126 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 127 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 128 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 129 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 130 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 131 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 132 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 133 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 134 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 135 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 136 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 137 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 138 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 139 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 140 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 141 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 142 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 143 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 144 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 145 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 146 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 147 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 148 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 149 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 150 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 151 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 152 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 153 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 154 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 155 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 156 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 157 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 158 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 159 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 160 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 161 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 162 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 163 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 164 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 165 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 166 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 167 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 168 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 169 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 170 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 171 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 172 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 173 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 174 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 175 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 176 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 177 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 178 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 179 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 180 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 181 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 182 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 183 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 184 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 185 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 186 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 187 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 188 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 189 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 190 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 191 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 192 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 193 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 194 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 195 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 196 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 197 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 198 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 199 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 200 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 201 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 202 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 203 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 204 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 205 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 206 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 207 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 208 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 209 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 210 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 211 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 212 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 213 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 214 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 215 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 216 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 217 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 218 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 219 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 220 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 221 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 222 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 223 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 224 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 225 / 2925
  File: jw01666001001_02102_00001-seg001_nrcblong_o001_crfints.fits   Frame: 226 / 2925

## Step 2 — Show all headers from the first file found

In [13]:
import pandas as pd
pd.set_option('display.max_colwidth', None)
pd.set_option('display.max_rows', None)

# Grab the first available file to inspect headers
all_files = (
    list(original_path.glob("jw01666001001*_nrcb1/*crfints.fits")) +
    list(original_path.glob("jw01666001001*_nrcblong/*crfints.fits"))
)

if not all_files:
    print("No files found. Check your original_path.")
else:
    filepath = all_files[0]
    print(f"Inspecting: {filepath.name}\n")

    with fits.open(filepath) as f:
        print("Extensions in this file:")
        f.info()
        print()

        for i, hdu in enumerate(f):
            ext_name = hdu.name if hdu.name else f"Extension {i}"
            print(f"\n{'='*60}")
            print(f"  EXTENSION {i}: {ext_name}")
            print(f"{'='*60}")
            rows = [
                {
                    "Keyword": key,
                    "Value": str(value),
                    "Comment": hdu.header.comments[key]
                }
                for key, value in hdu.header.items()
                if key.strip()
            ]
            if rows:
                display(pd.DataFrame(rows))
            else:
                print("  (no headers)")

Inspecting: jw01666001001_02102_00001-seg001_nrcb1_o001_crfints.fits

Extensions in this file:
Filename: T:\JWST-Timing\MAST_2023-10-07T0548\JWST\jw01666001001_02102_00001-seg001_nrcb1\jw01666001001_02102_00001-seg001_nrcb1_o001_crfints.fits
No.    Name      Ver    Type      Cards   Dimensions   Format
  0  PRIMARY       1 PrimaryHDU     348   ()
  1  SCI           1 ImageHDU        83   (160, 160, 2925)   float32
  2  ERR           1 ImageHDU        11   (160, 160, 2925)   float32
  3  DQ            1 ImageHDU        12   (160, 160, 2925)   int32 (rescales to uint32)
  4  AREA          1 ImageHDU         9   (160, 160)   float32
  5  INT_TIMES     1 BinTableHDU     24   2925R x 7C   [J, D, D, D, D, D, D]
  6  VAR_POISSON    1 ImageHDU        10   (160, 160, 2925)   float32
  7  VAR_RNOISE    1 ImageHDU        10   (160, 160, 2925)   float32
  8  VAR_FLAT      1 ImageHDU        10   (160, 160, 2925)   float32
  9  ASDF          1 BinTableHDU     11   1R x 1C   [25754B]


============================================================
  EXTENSION 0: PRIMARY
============================================================

,Keyword,Value,Comment
0,SIMPLE,True,conforms to FITS standard
1,BITPIX,8,array data type
2,NAXIS,0,number of array dimensions
3,EXTEND,True,
4,DATE,2023-08-26T02:30:19.372,UTC date file created
5,ORIGIN,STSCI,Organization responsible for creating file
6,TIMESYS,UTC,principal time system for time-related keywords
7,TIMEUNIT,s,Default unit applicable to all time values
8,FILENAME,jw01666001001_02102_00001-seg001_nrcb1_o001_crfints.fits,Name of t
9,SDP_VER,2023_2a,Data processing (DP) Software Version
10,PRD_VER,PRDOPSSOC-062,S&OC Project Reference Database (PRD) Version
11,OSS_VER,008.005.000.000,Observatory Scheduling Software (OSS) Version
12,GSC_VER,GSC2431,Guide Star Catalog (GSC) Version
13,CAL_VER,1.11.4,Calibration Software Version
14,CAL_VCS,RELEASE,Calibration software version control sys number
15,DATAMODL,CubeModel,Type of data model
16,TELESCOP,JWST,Telescope used to acquire the data
17,HGA_MOVE,False,High Gain Antenna moved during data collection
18,PWFSEET,59979.57104056713,Previous WFS exposure end time
19,NWFSEST,59981.25749706019,Next WFS exposure start time
20,COMPRESS,False,On-board data compression was used (T/F)
21,ASNPOOL,jw01666_20230825t220040_pool.csv,Name of the ASN pool
22,ASNTABLE,jw01666-o001_20230825t220040_tso3_00002_asn.json,Name of the ASN t
23,TITLE,Validating JWST's in-orbit clock accuracy,Proposal title
24,PI_NAME,"Gandhi, Poshak",Principal investigator name
25,CATEGORY,GO,Program category
26,SCICAT,Stellar Physics and Stellar Types,Science category assigned during
27,DATE-OBS,2023-02-05,[yyyy-mm-dd] UTC date at start of exposure
28,TIME-OBS,19:02:07.281,[hh:mm:ss.sss] UTC time at start of exposure
29,DATE-BEG,2023-02-05T19:02:07.281,Date-time start of exposure
30,DATE-END,2023-02-06T04:28:41.361,Date-time end of exposure
31,OBS_ID,V01666001001P0000000002102,Programmatic observation identifier
32,VISIT_ID,01666001001,Visit identifier
33,PROGRAM,01666,Program number
34,OBSERVTN,001,Observation number
35,VISIT,001,Visit number
36,VISITGRP,02,Visit group identifier
37,SEQ_ID,1,Parallel sequence identifier
38,ACT_ID,02,Activity identifier
39,EXPOSURE,1,Exposure request number
40,BKGDTARG,False,Background target
41,TEMPLATE,NIRCam Time Series,Observation template used
42,OBSLABEL,Time Series Mode,Proposer label for the observation
43,ENG_QUAL,OK,Engineering data quality indicator from EngDB
44,ENGQLPTG,CALCULATED_TRACK_TR_202111,Quality of pointing information from En
45,VISITYPE,PRIME_TARGETED_FIXED,Visit type
46,VSTSTART,2023-02-05 18:26:18.1000000,UTC visit start time
47,VISITSTA,SUCCESSFUL,Status of a visit
48,NEXPOSUR,1,Total number of planned exposures in visit
49,INTARGET,False,At least one exposure in visit is internal
50,TARGOOPP,False,Visit scheduled as target of opportunity
51,TSOVISIT,True,Time Series Observation visit indicator
52,EXP_ONLY,False,Special commanding without SI configuration
53,CROWDFLD,False,Are the FGSes in a crowded field?
54,TARGPROP,NAME-ZTF-J153932.16+502738.8,Proposer's name for the target
55,TARGNAME,NAME ZTF J153932.16+502738.8,Standard astronomical catalog name fo
56,TARGTYPE,FIXED,"Type of target (fixed, moving, generic)"
57,TARGCAT,Star,Target category from APT
58,TARGDESC,Compact binary systems; White dwarfs,Target description from APT
59,TARG_RA,234.8839607668344,Target RA at mid time of exposure
60,TARG_DEC,50.46074748597033,Target Dec at mid time of exposure
61,TARGURA,0.1,Target RA uncertainty
62,TARGUDEC,0.1,Target Dec uncertainty
63,MU_RA,-0.00341300007424388,Target proper motion in RA
64,MU_DEC,-0.00382299995180801,Target proper motion in Dec
65,MU_EPOCH,2015-07-02 12:00:00.0000000,Target proper motion epoch
66,PROP_RA,234.8839720833333,Proposer's target RA
67,PROP_DEC,50.46075555555556,Proposer's target Dec
68,INSTRUME,NIRCAM,Instrument used to acquire the data
69,DETECTOR,NRCB1,Name of detector used to acquire the data
70,MODULE,B,"NIRCam module: A, B, or MULTIPLE"
71,CHANNEL,SHORT,Instrument channel
72,FILTER,F070W,Name of the filter element used
73,PUPIL,CLEAR,Name of the pupil element used
74,PILIN,False,Pupil imaging lens in the optical path?
75,CORONMSK,NONE,coronagraph mask used
76,OPMODE,NONE,Lamp operating mode
77,EXPCOUNT,1,Running count of exposures in visit
78,EXPRIPAR,PRIME,Prime or parallel exposure
79,EXP_TYPE,NRC_TSIMAGE,Type of data in the exposure
80,EXPSTART,59980.79313982639,[d] exposure start time in MJD
81,EXPMID,59980.98986482639,[d] exposure mid time in MJD
82,EXPEND,59981.18658982639,[d] exposure end time in MJD
83,OSF_FILE,2023037T053330659_002_osf.xml,Observatory Status File name coverin
84,READPATT,BRIGHT1,Readout pattern
85,EXSEGNUM,1,Sequential segment number
86,EXSEGTOT,3,Total number of segments
87,NOUTPUTS,1,Number of detector outputs used
88,NINTS,6100,Number of integrations in exposure
89,INTSTART,1,Starting integration number in this segment
90,INTEND,2925,Ending integration number in this segment
91,NGROUPS,10,Number of groups in integration
92,NFRAMES,1,Number of frames per group
93,FRMDIVSR,1,Divisor applied to frame-averaged groups
94,GROUPGAP,1,Number of frames dropped between groups
95,DRPFRMS1,0,Frames dropped prior to first integration
96,DRPFRMS3,0,Frames dropped between integrations
97,NSAMPLES,1,Number of A/D samples per pixel
98,TSAMPLE,10.0,[us] Time between samples
99,TFRAME,0.27864,[s] Time between frames
100,TGROUP,0.55728,[s] Time between groups
101,EFFINTTM,5.294160000000001,[s] Effective integration time
102,EFFEXPTM,32294.376,[s] Effective exposure time
103,DURATION,34025.312,[s] Total duration of exposure
104,NRSTSTRT,1,Number of resets at start of exposure
105,NRESETS,1,Number of resets between integrations
106,ZEROFRAM,False,Zero frame was downlinked separately
107,DATAPROB,False,Science telemetry indicated a problem
108,SCA_NUM,486,Sensor Chip Assembly number
109,DATAMODE,32,post-processing method used in FPAP
110,SCTARATE,0.000515323378936541,[ms/s] Spacecraft Clock Time Adjust RATE
111,IS_PSF,False,exposure is PSF reference
112,SELFREF,False,self-referencing PSF
113,PRIMECRS,0.07856223257368103,Cosmic Ray rate per thousand pixels per second
114,EXTNCRS,0.0,Snowballs/showers per million pixels per second
115,SUBARRAY,SUB160P,Subarray used
116,SUBSTRT1,1803,Starting pixel in axis 1 direction
117,SUBSTRT2,1769,Starting pixel in axis 2 direction
118,SUBSIZE1,160,Number of pixels in axis 1 direction
119,SUBSIZE2,160,Number of pixels in axis 2 direction
120,FASTAXIS,1,Fast readout axis direction
121,SLOWAXIS,-2,Slow readout axis direction
122,PATTTYPE,NONE,Primary dither pattern type
123,PATT_NUM,1,Position number within dither pattern
124,NUMDTHPT,1,Total number of points in pattern
125,XOFFSET,3.81595281818908e-13,x offset from pattern starting position
126,YOFFSET,7.08258719294425e-11,y offset from pattern starting position
127,APERNAME,NRCB1_SUB160P,PRD science aperture used
128,PPS_APER,NRCB5_SUB160P,original AperName supplied by PPS
129,VA_RA,234.88231433423329,[deg] Velocity aberrated apparent reference RA
130,VA_DEC,50.45552262609792,[deg] Velocity aberrated apparent reference Dec
131,BARTDELT,142.3970103962347,[s] Barycentric correction at exposure start
132,BSTRTIME,59980.79478793994,[d] Barycentric exposure start time in MJD
133,BENDTIME,59981.18825315557,[d] Barycentric exposure end time in MJD
134,BMIDTIME,59980.99152055235,[d] Barycentric exposure mid time in MJD
135,HELIDELT,140.6342798145488,[s] Heliocentric correction at exposure start
136,HSTRTIME,59980.79476753796,[d] Heliocentric exposure start time in MJD
137,HENDTIME,59981.18823275121,[d] Heliocentric exposure end time in MJD
138,HMIDTIME,59980.99150014918,[d] Heliocentric exposure mid time in MJD
139,FAM_LA1,0,position in steps of linear actuator 1
140,FASTEP1,0,requested focus actuator 1 starting steps
141,FAUNIT1,0.0,requested focus actuator 1 starting units
142,FAPHASE1,NULL,requested focus actuator 1 starting phase
143,FA1VALUE,0,requested focus actuator 1 position value
144,FAM_LA2,0,position in steps of linear actuator 2
145,FASTEP2,0,requested focus actuator 2 starting steps
146,FAUNIT2,0.0,requested focus actuator 2 starting units
147,FAPHASE2,NULL,requested focus actuator 2 starting phase
148,FA2VALUE,0,requested focus actuator 2 position value
149,FAM_LA3,0,position in steps of linear actuator 3
150,FASTEP3,0,requested focus actuator 3 starting steps
151,FAUNIT3,0.0,requested focus actuator 3 starting units
152,FAPHASE3,NULL,requested focus actuator 3 starting phase
153,FA3VALUE,0,requested focus actuator 3 position value
154,GS_ORDER,1,index of guide star within list of selected gui
155,GSSTRTTM,2023-02-05 18:53:54.9310000,UTC time when guide star activity star
156,GSENDTIM,2023-02-05 18:57:57.6190000,UTC time when guide star activity comp
157,GDSTARID,N60S010581,guide star identifier
158,GS_RA,235.0273286624808,guide star right ascension
159,GS_DEC,50.48611961914964,guide star declination
160,GS_URA,0.000219293609261512,guide star right ascension uncertainty
161,GS_UDEC,0.000221558824181556,guide star declination uncertainty
162,GS_MAG,16.63854598999023,guide star magnitude in FGS detector
163,GS_UMAG,0.09138740599155426,guide star magnitude uncertainty
164,GS_V3_PA,284.973177007083,V3 Position Angle of guide star for science
165,PCS_MODE,FINEGUIDE,Pointing Control System mode
166,VISITEND,2023-02-06 04:29:44.6570000,Observatory UTC time when the visit co
167,CRDS_VER,11.17.2,Version of CRDS file selection software used
168,CRDS_CTX,jwst_1118.pmap,CRDS context (.pmap) used to select ref files
169,R_AREA,crds://jwst_nircam_area_0036.fits,Pixel area reference file name
170,R_CAMERA,N/A,Nirspec Camera reference file name
171,R_COLLIM,N/A,Nirspec Collimator reference file name
172,R_DARK,crds://jwst_nircam_dark_0313.fits,Dark reference file name
173,R_DISPER,N/A,Disperser reference file name
174,R_DISTOR,crds://jwst_nircam_distortion_0161.asdf,Distortion reference file
175,R_FILOFF,crds://jwst_nircam_filteroffset_0006.asdf,Filter Offset reference
176,R_FLAT,crds://jwst_nircam_flat_0468.fits,Flat reference file name
177,R_DFLAT,N/A,DFlat reference file name
178,R_FFLAT,N/A,FFlat reference file name
179,R_SFLAT,N/A,SFlat reference file name
180,R_FORE,N/A,Nirspec FORE Model reference file name
181,R_FPA,N/A,Nirspec FPA Model reference file name
182,R_GAIN,crds://jwst_nircam_gain_0090.fits,Gain reference file name
183,R_IFUFOR,N/A,ifufore reference file name
184,R_IFUPOS,N/A,ifupost reference file name
185,R_IFUSLI,N/A,ifuslicer reference file name
186,R_LINEAR,crds://jwst_nircam_linearity_0057.fits,Linearity reference file na
187,R_MASK,crds://jwst_nircam_mask_0060.fits,Mask reference file name
188,R_MSA,N/A,Nirspec MSA Model reference file name
189,R_OTE,N/A,Nirspec OTE Model reference file name
190,R_PHOTOM,crds://jwst_nircam_photom_0118.fits,Photometric reference file nam
191,R_READNO,crds://jwst_nircam_readnoise_0165.fits,Read noise reference file n
192,R_REGION,N/A,Regions reference file name
193,R_SATURA,crds://jwst_nircam_saturation_0102.fits,Saturation reference file
194,R_SPCWCS,N/A,Spectral distortion reference file name
195,R_SUPERB,crds://jwst_nircam_superbias_0154.fits,Superbias reference file na
196,R_WAVRAN,N/A,Wavelength Range reference file name
197,S_WCS,COMPLETE,Assign World Coordinate System
198,S_DARK,COMPLETE,Dark Subtraction
199,S_DQINIT,COMPLETE,Data Quality Initialization
200,S_FLAT,COMPLETE,Flat Field Correction
201,S_GANSCL,SKIPPED,Gain Scale Correction
202,S_GRPSCL,SKIPPED,Group Scale Correction
203,S_IPC,SKIPPED,Interpixel Capacitance Correction
204,S_JUMP,COMPLETE,Jump Detection
205,S_LINEAR,COMPLETE,Linearity Correction
206,S_OUTLIR,COMPLETE,Outlier Detection
207,S_PERSIS,SKIPPED,Persistence Correction
208,S_PHOTOM,COMPLETE,Photometric Calibration
209,S_RAMP,COMPLETE,Ramp Fitting
210,S_REFPIX,COMPLETE,Reference Pixel Correction
211,S_SATURA,COMPLETE,Saturation Checking
212,S_SUPERB,COMPLETE,Superbias Subtraction

============================================================
  EXTENSION 1: SCI
============================================================

,Keyword,Value,Comment
0,XTENSION,IMAGE,Image extension
1,BITPIX,-32,array data type
2,NAXIS,3,number of array dimensions
3,NAXIS1,160,
4,NAXIS2,160,
5,NAXIS3,2925,
6,PCOUNT,0,number of parameters
7,GCOUNT,1,number of groups
8,EXTNAME,SCI,extension name
9,MJD-BEG,59980.79313982639,[d] exposure start time in MJD
10,MJD-AVG,59980.98986482639,[d] exposure mid-point in MJD
11,MJD-END,59981.18658982639,[d] exposure end time in MJD
12,TDB-BEG,59980.79478793945,[d] TDB time of exposure start in MJD
13,TDB-MID,59980.99152055186,[d] TDB time of exposure mid-point in MJD
14,TDB-END,59981.18825315506,[d] TDB time of exposure end in MJD
15,XPOSURE,32294.376,[s] Effective exposure time
16,TELAPSE,34025.312,[s] Total elapsed exposure time
17,REFFRAME,EME2000,Ephemeris reference frame
18,EPH_TYPE,Definitive,Definitive or Predicted
19,EPH_TIME,59980.98986482639,[d] MJD time of position and velocity vectors
20,JWST_X,-109076334.2464736,[km] barycentric JWST X coordinate at MJD_AVG
21,JWST_Y,94433294.73403105,[km] barycentric JWST Y coordinate at MJD_AVG
22,JWST_Z,40686882.92015418,[km] barycentric JWST Z coordinate at MJD_AVG
23,OBSGEO-X,-580663789.590796,[m] geocentric JWST X coordinate at MJD_AVG
24,OBSGEO-Y,1473223684.96429,[m] geocentric JWST Y coordinate at MJD_AVG
25,OBSGEO-Z,354800456.4779049,[m] geocentric JWST Z coordinate at MJD_AVG
26,JWST_DX,-21.10697522235143,[km/s] barycentric JWST X velocity at MJD_AVG
27,JWST_DY,-20.12429662062409,[km/s] barycentric JWST Y velocity at MJD_AVG
28,JWST_DZ,-8.577994074587187,[km/s] barycentric JWST Z velocity at MJD_AVG
29,OBSGEODX,-161.5196697606875,[m/s] geocentric JWST X velocity at MJD_AVG
30,OBSGEODY,-159.9559942000606,[m/s] geocentric JWST Y velocity at MJD_AVG
31,OBSGEODZ,75.94138735884412,[m/s] geocentric JWST Z velocity at MJD_AVG
32,PA_APER,285.32540230903925,[deg] Position angle of aperture used
33,VA_SCALE,1.0000386769867462,Velocity aberration scale factor
34,BUNIT,MJy/sr,physical units of the array values
35,PHOTMJSR,4.473999977111816,Flux density (MJy/steradian) producing 1 cps
36,PHOTUJA2,105.15882169395023,Flux density (uJy/arcsec2) producing 1 cps
37,PIXAR_SR,2.23e-14,Nominal pixel area in steradians
38,PIXAR_A2,0.0009453,Nominal pixel area in arcsec^2
39,RADESYS,ICRS,Name of the coordinate reference frame
40,RA_V1,234.71809989889192,[deg] RA of telescope V1 axis
41,DEC_V1,50.53132712831115,[deg] Dec of telescope V1 axis
42,PA_V3,284.73446821210723,[deg] Position angle of telescope V3 axis
43,WCSAXES,2,number of World Coordinate System axes
44,CRPIX1,80.31,axis 1 coordinate of the reference pixel
45,CRPIX2,78.22,axis 2 coordinate of the reference pixel
46,CRVAL1,234.88402868566,first axis value at the reference pixel
47,CRVAL2,50.460781371758,second axis value at the reference pixel
48,CTYPE1,RA---TAN,Axis 1 type
49,CTYPE2,DEC--TAN,Axis 2 type
50,CUNIT1,deg,Axis 1 units
51,CUNIT2,deg,Axis 2 units
52,CD1_1,-2.2760461514651e-06,"linear transformation matrix element, CD matrix"
53,CD1_2,-8.2141376211297e-06,"linear transformation matrix element, CD matrix"
54,CD2_1,-8.1887964829095e-06,"linear transformation matrix element, CD matrix"
55,CD2_2,2.2507707297963e-06,"linear transformation matrix element, CD matrix"
56,S_REGION,POLYGON ICRS 234.885308603 50.461257165 234.883243861 50.461616824 234.882672078 50.460307089 234.884736286 50.459946489,spatial extent of the observation
57,V2_REF,-148.485879,[arcsec] Telescope V2 coord of reference point
58,V3_REF,-432.237215,[arcsec] Telescope V3 coord of reference point
59,VPARITY,-1,Relative sense of rotation between Ideal xy and
60,V3I_YANG,0.4629549,[deg] Angle from V3 axis to Ideal y axis
61,RA_REF,234.8840220631934,[deg] Right ascension of the reference point
62,DEC_REF,50.460781925725826,[deg] Declination of the reference point
63,ROLL_REF,284.86244740903925,[deg] V3 roll angle at the ref point (N over E)
64,VELOSYS,-11593.45,[m/s] Barycentric correction to radial velocity
65,XREF_SCI,80.31,Aperture X reference point in SCI frame
66,YREF_SCI,78.22,Aperture Y reference point in SCI frame
67,EXTVER,1,extension value

============================================================
  EXTENSION 2: ERR
============================================================

     Keyword   Value                             Comment
0   XTENSION   IMAGE                     Image extension
1     BITPIX     -32                     array data type
2      NAXIS       3          number of array dimensions
3     NAXIS1     160
4     NAXIS2     160
5     NAXIS3    2925
6     PCOUNT       0                number of parameters
7     GCOUNT       1                    number of groups
8    EXTNAME     ERR                      extension name
9      BUNIT  MJy/sr  physical units of the array values
10    EXTVER       1                     extension value

============================================================
  EXTENSION 3: DQ
============================================================

     Keyword       Value                     Comment
0   XTENSION       IMAGE             Image extension
1     BITPIX          32             array data type
2      NAXIS           3  number of array dimensions
3     NAXIS1         160
4     NAXIS2         160
5     NAXIS3        2925
6     PCOUNT           0        number of parameters
7     GCOUNT           1            number of groups
8     BSCALE           1
9      BZERO  2147483648
10   EXTNAME          DQ              extension name
11    EXTVER           1             extension value

============================================================
  EXTENSION 4: AREA
============================================================

    Keyword  Value                     Comment
0  XTENSION  IMAGE             Image extension
1    BITPIX    -32             array data type
2     NAXIS      2  number of array dimensions
3    NAXIS1    160
4    NAXIS2    160
5    PCOUNT      0        number of parameters
6    GCOUNT      1            number of groups
7   EXTNAME   AREA              extension name
8    EXTVER      1             extension value

============================================================
  EXTENSION 5: INT_TIMES
============================================================

     Keyword               Value                     Comment
0   XTENSION            BINTABLE      binary table extension
1     BITPIX                   8             array data type
2      NAXIS                   2  number of array dimensions
3     NAXIS1                  52       length of dimension 1
4     NAXIS2                2925       length of dimension 2
5     PCOUNT                   0  number of group parameters
6     GCOUNT                   1            number of groups
7    TFIELDS                   7      number of table fields
8    EXTNAME           INT_TIMES              extension name
9     EXTVER                   1             extension value
10    TTYPE1  integration_number
11    TFORM1                   J
12    TTYPE2   int_start_MJD_UTC
13    TFORM2                   D
14    TTYPE3     int_mid_MJD_UTC
15    TFORM3                   D
16    TTYPE4     int_end_MJD_UTC
17    TFORM4                   D
18    TTYPE5   int_start_BJD_TDB
19    TFORM5                   D
20    TTYPE6     int_mid_BJD_TDB
21    TFORM6                   D
22    TTYPE7     int_end_BJD_TDB
23    TFORM7                   D

============================================================
  EXTENSION 6: VAR_POISSON
============================================================

    Keyword        Value                     Comment
0  XTENSION        IMAGE             Image extension
1    BITPIX          -32             array data type
2     NAXIS            3  number of array dimensions
3    NAXIS1          160
4    NAXIS2          160
5    NAXIS3         2925
6    PCOUNT            0        number of parameters
7    GCOUNT            1            number of groups
8   EXTNAME  VAR_POISSON              extension name
9    EXTVER            1             extension value

============================================================
  EXTENSION 7: VAR_RNOISE
============================================================

    Keyword       Value                     Comment
0  XTENSION       IMAGE             Image extension
1    BITPIX         -32             array data type
2     NAXIS           3  number of array dimensions
3    NAXIS1         160
4    NAXIS2         160
5    NAXIS3        2925
6    PCOUNT           0        number of parameters
7    GCOUNT           1            number of groups
8   EXTNAME  VAR_RNOISE              extension name
9    EXTVER           1             extension value

============================================================
  EXTENSION 8: VAR_FLAT
============================================================

    Keyword     Value                     Comment
0  XTENSION     IMAGE             Image extension
1    BITPIX       -32             array data type
2     NAXIS         3  number of array dimensions
3    NAXIS1       160
4    NAXIS2       160
5    NAXIS3      2925
6    PCOUNT         0        number of parameters
7    GCOUNT         1            number of groups
8   EXTNAME  VAR_FLAT              extension name
9    EXTVER         1             extension value

============================================================
  EXTENSION 9: ASDF
============================================================

     Keyword          Value                     Comment
0   XTENSION       BINTABLE      binary table extension
1     BITPIX              8             array data type
2      NAXIS              2  number of array dimensions
3     NAXIS1          25754       length of dimension 1
4     NAXIS2              1       length of dimension 2
5     PCOUNT              0  number of group parameters
6     GCOUNT              1            number of groups
7    TFIELDS              1      number of table fields
8     TTYPE1  ASDF_METADATA
9     TFORM1         25754B
10   EXTNAME           ASDF              extension name

## Step 3 — Export all headers to CSV

In [14]:
if all_files:
    all_rows = []
    with fits.open(filepath) as f:
        for i, hdu in enumerate(f):
            ext_name = hdu.name if hdu.name else f"Extension {i}"
            for key, value in hdu.header.items():
                if key.strip():
                    all_rows.append({
                        "Extension": ext_name,
                        "Keyword": key,
                        "Value": str(value),
                        "Comment": hdu.header.comments[key]
                    })

    df_all = pd.DataFrame(all_rows)
    df_all.to_csv("fits_headers.csv", index=False)
    print(f"Saved {len(df_all)} header entries to fits_headers.csv")
    display(df_all)

Saved 378 header entries to fits_headers.csv

,Extension,Keyword,Value,Comment
0,PRIMARY,SIMPLE,True,conforms to FITS standard
1,PRIMARY,BITPIX,8,array data type
2,PRIMARY,NAXIS,0,number of array dimensions
3,PRIMARY,EXTEND,True,
4,PRIMARY,DATE,2023-08-26T02:30:19.372,UTC date file created
5,PRIMARY,ORIGIN,STSCI,Organization responsible for creating file
6,PRIMARY,TIMESYS,UTC,principal time system for time-related keywords
7,PRIMARY,TIMEUNIT,s,Default unit applicable to all time values
8,PRIMARY,FILENAME,jw01666001001_02102_00001-seg001_nrcb1_o001_crfints.fits,Name of t
9,PRIMARY,SDP_VER,2023_2a,Data processing (DP) Software Version
10,PRIMARY,PRD_VER,PRDOPSSOC-062,S&OC Project Reference Database (PRD) Version
11,PRIMARY,OSS_VER,008.005.000.000,Observatory Scheduling Software (OSS) Version
12,PRIMARY,GSC_VER,GSC2431,Guide Star Catalog (GSC) Version
13,PRIMARY,CAL_VER,1.11.4,Calibration Software Version
14,PRIMARY,CAL_VCS,RELEASE,Calibration software version control sys number
15,PRIMARY,DATAMODL,CubeModel,Type of data model
16,PRIMARY,TELESCOP,JWST,Telescope used to acquire the data
17,PRIMARY,HGA_MOVE,False,High Gain Antenna moved during data collection
18,PRIMARY,PWFSEET,59979.57104056713,Previous WFS exposure end time
19,PRIMARY,NWFSEST,59981.25749706019,Next WFS exposure start time
20,PRIMARY,COMPRESS,False,On-board data compression was used (T/F)
21,PRIMARY,ASNPOOL,jw01666_20230825t220040_pool.csv,Name of the ASN pool
22,PRIMARY,ASNTABLE,jw01666-o001_20230825t220040_tso3_00002_asn.json,Name of the ASN t
23,PRIMARY,TITLE,Validating JWST's in-orbit clock accuracy,Proposal title
24,PRIMARY,PI_NAME,"Gandhi, Poshak",Principal investigator name
25,PRIMARY,CATEGORY,GO,Program category
26,PRIMARY,SCICAT,Stellar Physics and Stellar Types,Science category assigned during
27,PRIMARY,DATE-OBS,2023-02-05,[yyyy-mm-dd] UTC date at start of exposure
28,PRIMARY,TIME-OBS,19:02:07.281,[hh:mm:ss.sss] UTC time at start of exposure
29,PRIMARY,DATE-BEG,2023-02-05T19:02:07.281,Date-time start of exposure
30,PRIMARY,DATE-END,2023-02-06T04:28:41.361,Date-time end of exposure
31,PRIMARY,OBS_ID,V01666001001P0000000002102,Programmatic observation identifier
32,PRIMARY,VISIT_ID,01666001001,Visit identifier
33,PRIMARY,PROGRAM,01666,Program number
34,PRIMARY,OBSERVTN,001,Observation number
35,PRIMARY,VISIT,001,Visit number
36,PRIMARY,VISITGRP,02,Visit group identifier
37,PRIMARY,SEQ_ID,1,Parallel sequence identifier
38,PRIMARY,ACT_ID,02,Activity identifier
39,PRIMARY,EXPOSURE,1,Exposure request number
40,PRIMARY,BKGDTARG,False,Background target
41,PRIMARY,TEMPLATE,NIRCam Time Series,Observation template used
42,PRIMARY,OBSLABEL,Time Series Mode,Proposer label for the observation
43,PRIMARY,ENG_QUAL,OK,Engineering data quality indicator from EngDB
44,PRIMARY,ENGQLPTG,CALCULATED_TRACK_TR_202111,Quality of pointing information from En
45,PRIMARY,VISITYPE,PRIME_TARGETED_FIXED,Visit type
46,PRIMARY,VSTSTART,2023-02-05 18:26:18.1000000,UTC visit start time
47,PRIMARY,VISITSTA,SUCCESSFUL,Status of a visit
48,PRIMARY,NEXPOSUR,1,Total number of planned exposures in visit
49,PRIMARY,INTARGET,False,At least one exposure in visit is internal
50,PRIMARY,TARGOOPP,False,Visit scheduled as target of opportunity
51,PRIMARY,TSOVISIT,True,Time Series Observation visit indicator
52,PRIMARY,EXP_ONLY,False,Special commanding without SI configuration
53,PRIMARY,CROWDFLD,False,Are the FGSes in a crowded field?
54,PRIMARY,TARGPROP,NAME-ZTF-J153932.16+502738.8,Proposer's name for the target
55,PRIMARY,TARGNAME,NAME ZTF J153932.16+502738.8,Standard astronomical catalog name fo
56,PRIMARY,TARGTYPE,FIXED,"Type of target (fixed, moving, generic)"
57,PRIMARY,TARGCAT,Star,Target category from APT
58,PRIMARY,TARGDESC,Compact binary systems; White dwarfs,Target description from APT
59,PRIMARY,TARG_RA,234.8839607668344,Target RA at mid time of exposure
60,PRIMARY,TARG_DEC,50.46074748597033,Target Dec at mid time of exposure
61,PRIMARY,TARGURA,0.1,Target RA uncertainty
62,PRIMARY,TARGUDEC,0.1,Target Dec uncertainty
63,PRIMARY,MU_RA,-0.00341300007424388,Target proper motion in RA
64,PRIMARY,MU_DEC,-0.00382299995180801,Target proper motion in Dec
65,PRIMARY,MU_EPOCH,2015-07-02 12:00:00.0000000,Target proper motion epoch
66,PRIMARY,PROP_RA,234.8839720833333,Proposer's target RA
67,PRIMARY,PROP_DEC,50.46075555555556,Proposer's target Dec
68,PRIMARY,INSTRUME,NIRCAM,Instrument used to acquire the data
69,PRIMARY,DETECTOR,NRCB1,Name of detector used to acquire the data
70,PRIMARY,MODULE,B,"NIRCam module: A, B, or MULTIPLE"
71,PRIMARY,CHANNEL,SHORT,Instrument channel
72,PRIMARY,FILTER,F070W,Name of the filter element used
73,PRIMARY,PUPIL,CLEAR,Name of the pupil element used
74,PRIMARY,PILIN,False,Pupil imaging lens in the optical path?
75,PRIMARY,CORONMSK,NONE,coronagraph mask used
76,PRIMARY,OPMODE,NONE,Lamp operating mode
77,PRIMARY,EXPCOUNT,1,Running count of exposures in visit
78,PRIMARY,EXPRIPAR,PRIME,Prime or parallel exposure
79,PRIMARY,EXP_TYPE,NRC_TSIMAGE,Type of data in the exposure
80,PRIMARY,EXPSTART,59980.79313982639,[d] exposure start time in MJD
81,PRIMARY,EXPMID,59980.98986482639,[d] exposure mid time in MJD
82,PRIMARY,EXPEND,59981.18658982639,[d] exposure end time in MJD
83,PRIMARY,OSF_FILE,2023037T053330659_002_osf.xml,Observatory Status File name coverin
84,PRIMARY,READPATT,BRIGHT1,Readout pattern
85,PRIMARY,EXSEGNUM,1,Sequential segment number
86,PRIMARY,EXSEGTOT,3,Total number of segments
87,PRIMARY,NOUTPUTS,1,Number of detector outputs used
88,PRIMARY,NINTS,6100,Number of integrations in exposure
89,PRIMARY,INTSTART,1,Starting integration number in this segment
90,PRIMARY,INTEND,2925,Ending integration number in this segment
91,PRIMARY,NGROUPS,10,Number of groups in integration
92,PRIMARY,NFRAMES,1,Number of frames per group
93,PRIMARY,FRMDIVSR,1,Divisor applied to frame-averaged groups
94,PRIMARY,GROUPGAP,1,Number of frames dropped between groups
95,PRIMARY,DRPFRMS1,0,Frames dropped prior to first integration
96,PRIMARY,DRPFRMS3,0,Frames dropped between integrations
97,PRIMARY,NSAMPLES,1,Number of A/D samples per pixel
98,PRIMARY,TSAMPLE,10.0,[us] Time between samples
99,PRIMARY,TFRAME,0.27864,[s] Time between frames
100,PRIMARY,TGROUP,0.55728,[s] Time between groups
101,PRIMARY,EFFINTTM,5.294160000000001,[s] Effective integration time
102,PRIMARY,EFFEXPTM,32294.376,[s] Effective exposure time
103,PRIMARY,DURATION,34025.312,[s] Total duration of exposure
104,PRIMARY,NRSTSTRT,1,Number of resets at start of exposure
105,PRIMARY,NRESETS,1,Number of resets between integrations
106,PRIMARY,ZEROFRAM,False,Zero frame was downlinked separately
107,PRIMARY,DATAPROB,False,Science telemetry indicated a problem
108,PRIMARY,SCA_NUM,486,Sensor Chip Assembly number
109,PRIMARY,DATAMODE,32,post-processing method used in FPAP
110,PRIMARY,SCTARATE,0.000515323378936541,[ms/s] Spacecraft Clock Time Adjust RATE
111,PRIMARY,IS_PSF,False,exposure is PSF reference
112,PRIMARY,SELFREF,False,self-referencing PSF
113,PRIMARY,PRIMECRS,0.07856223257368103,Cosmic Ray rate per thousand pixels per second
114,PRIMARY,EXTNCRS,0.0,Snowballs/showers per million pixels per second
115,PRIMARY,SUBARRAY,SUB160P,Subarray used
116,PRIMARY,SUBSTRT1,1803,Starting pixel in axis 1 direction
117,PRIMARY,SUBSTRT2,1769,Starting pixel in axis 2 direction
118,PRIMARY,SUBSIZE1,160,Number of pixels in axis 1 direction
119,PRIMARY,SUBSIZE2,160,Number of pixels in axis 2 direction
120,PRIMARY,FASTAXIS,1,Fast readout axis direction
121,PRIMARY,SLOWAXIS,-2,Slow readout axis direction
122,PRIMARY,PATTTYPE,NONE,Primary dither pattern type
123,PRIMARY,PATT_NUM,1,Position number within dither pattern
124,PRIMARY,NUMDTHPT,1,Total number of points in pattern
125,PRIMARY,XOFFSET,3.81595281818908e-13,x offset from pattern starting position
126,PRIMARY,YOFFSET,7.08258719294425e-11,y offset from pattern starting position
127,PRIMARY,APERNAME,NRCB1_SUB160P,PRD science aperture used
128,PRIMARY,PPS_APER,NRCB5_SUB160P,original AperName supplied by PPS
129,PRIMARY,VA_RA,234.88231433423329,[deg] Velocity aberrated apparent reference RA
130,PRIMARY,VA_DEC,50.45552262609792,[deg] Velocity aberrated apparent reference Dec
131,PRIMARY,BARTDELT,142.3970103962347,[s] Barycentric correction at exposure start
132,PRIMARY,BSTRTIME,59980.79478793994,[d] Barycentric exposure start time in MJD
133,PRIMARY,BENDTIME,59981.18825315557,[d] Barycentric exposure end time in MJD
134,PRIMARY,BMIDTIME,59980.99152055235,[d] Barycentric exposure mid time in MJD
135,PRIMARY,HELIDELT,140.6342798145488,[s] Heliocentric correction at exposure start
136,PRIMARY,HSTRTIME,59980.79476753796,[d] Heliocentric exposure start time in MJD
137,PRIMARY,HENDTIME,59981.18823275121,[d] Heliocentric exposure end time in MJD
138,PRIMARY,HMIDTIME,59980.99150014918,[d] Heliocentric exposure mid time in MJD
139,PRIMARY,FAM_LA1,0,position in steps of linear actuator 1
140,PRIMARY,FASTEP1,0,requested focus actuator 1 starting steps
141,PRIMARY,FAUNIT1,0.0,requested focus actuator 1 starting units
142,PRIMARY,FAPHASE1,NULL,requested focus actuator 1 starting phase
143,PRIMARY,FA1VALUE,0,requested focus actuator 1 position value
144,PRIMARY,FAM_LA2,0,position in steps of linear actuator 2
145,PRIMARY,FASTEP2,0,requested focus actuator 2 starting steps
146,PRIMARY,FAUNIT2,0.0,requested focus actuator 2 starting units
147,PRIMARY,FAPHASE2,NULL,requested focus actuator 2 starting phase
148,PRIMARY,FA2VALUE,0,requested focus actuator 2 position value
149,PRIMARY,FAM_LA3,0,position in steps of linear actuator 3
150,PRIMARY,FASTEP3,0,requested focus actuator 3 starting steps
151,PRIMARY,FAUNIT3,0.0,requested focus actuator 3 starting units
152,PRIMARY,FAPHASE3,NULL,requested focus actuator 3 starting phase
153,PRIMARY,FA3VALUE,0,requested focus actuator 3 position value
154,PRIMARY,GS_ORDER,1,index of guide star within list of selected gui
155,PRIMARY,GSSTRTTM,2023-02-05 18:53:54.9310000,UTC time when guide star activity star
156,PRIMARY,GSENDTIM,2023-02-05 18:57:57.6190000,UTC time when guide star activity comp
157,PRIMARY,GDSTARID,N60S010581,guide star identifier
158,PRIMARY,GS_RA,235.0273286624808,guide star right ascension
159,PRIMARY,GS_DEC,50.48611961914964,guide star declination
160,PRIMARY,GS_URA,0.000219293609261512,guide star right ascension uncertainty
161,PRIMARY,GS_UDEC,0.000221558824181556,guide star declination uncertainty
162,PRIMARY,GS_MAG,16.63854598999023,guide star magnitude in FGS detector
163,PRIMARY,GS_UMAG,0.09138740599155426,guide star magnitude uncertainty
164,PRIMARY,GS_V3_PA,284.973177007083,V3 Position Angle of guide star for science
165,PRIMARY,PCS_MODE,FINEGUIDE,Pointing Control System mode
166,PRIMARY,VISITEND,2023-02-06 04:29:44.6570000,Observatory UTC time when the visit co
167,PRIMARY,CRDS_VER,11.17.2,Version of CRDS file selection software used
168,PRIMARY,CRDS_CTX,jwst_1118.pmap,CRDS context (.pmap) used to select ref files
169,PRIMARY,R_AREA,crds://jwst_nircam_area_0036.fits,Pixel area reference file name
170,PRIMARY,R_CAMERA,N/A,Nirspec Camera reference file name
171,PRIMARY,R_COLLIM,N/A,Nirspec Collimator reference file name
172,PRIMARY,R_DARK,crds://jwst_nircam_dark_0313.fits,Dark reference file name
173,PRIMARY,R_DISPER,N/A,Disperser reference file name
174,PRIMARY,R_DISTOR,crds://jwst_nircam_distortion_0161.asdf,Distortion reference file
175,PRIMARY,R_FILOFF,crds://jwst_nircam_filteroffset_0006.asdf,Filter Offset reference
176,PRIMARY,R_FLAT,crds://jwst_nircam_flat_0468.fits,Flat reference file name
177,PRIMARY,R_DFLAT,N/A,DFlat reference file name
178,PRIMARY,R_FFLAT,N/A,FFlat reference file name
179,PRIMARY,R_SFLAT,N/A,SFlat reference file name
180,PRIMARY,R_FORE,N/A,Nirspec FORE Model reference file name
181,PRIMARY,R_FPA,N/A,Nirspec FPA Model reference file name
182,PRIMARY,R_GAIN,crds://jwst_nircam_gain_0090.fits,Gain reference file name
183,PRIMARY,R_IFUFOR,N/A,ifufore reference file name
184,PRIMARY,R_IFUPOS,N/A,ifupost reference file name
185,PRIMARY,R_IFUSLI,N/A,ifuslicer reference file name
186,PRIMARY,R_LINEAR,crds://jwst_nircam_linearity_0057.fits,Linearity reference file na
187,PRIMARY,R_MASK,crds://jwst_nircam_mask_0060.fits,Mask reference file name
188,PRIMARY,R_MSA,N/A,Nirspec MSA Model reference file name
189,PRIMARY,R_OTE,N/A,Nirspec OTE Model reference file name
190,PRIMARY,R_PHOTOM,crds://jwst_nircam_photom_0118.fits,Photometric reference file nam
191,PRIMARY,R_READNO,crds://jwst_nircam_readnoise_0165.fits,Read noise reference file n
192,PRIMARY,R_REGION,N/A,Regions reference file name
193,PRIMARY,R_SATURA,crds://jwst_nircam_saturation_0102.fits,Saturation reference file
194,PRIMARY,R_SPCWCS,N/A,Spectral distortion reference file name
195,PRIMARY,R_SUPERB,crds://jwst_nircam_superbias_0154.fits,Superbias reference file na
196,PRIMARY,R_WAVRAN,N/A,Wavelength Range reference file name
197,PRIMARY,S_WCS,COMPLETE,Assign World Coordinate System
198,PRIMARY,S_DARK,COMPLETE,Dark Subtraction
199,PRIMARY,S_DQINIT,COMPLETE,Data Quality Initialization
200,PRIMARY,S_FLAT,COMPLETE,Flat Field Correction
201,PRIMARY,S_GANSCL,SKIPPED,Gain Scale Correction
202,PRIMARY,S_GRPSCL,SKIPPED,Group Scale Correction
203,PRIMARY,S_IPC,SKIPPED,Interpixel Capacitance Correction
204,PRIMARY,S_JUMP,COMPLETE,Jump Detection
205,PRIMARY,S_LINEAR,COMPLETE,Linearity Correction
206,PRIMARY,S_OUTLIR,COMPLETE,Outlier Detection
207,PRIMARY,S_PERSIS,SKIPPED,Persistence Correction
208,PRIMARY,S_PHOTOM,COMPLETE,Photometric Calibration
209,PRIMARY,S_RAMP,COMPLETE,Ramp Fitting
210,PRIMARY,S_REFPIX,COMPLETE,Reference Pixel Correction
211,PRIMARY,S_SATURA,COMPLETE,Saturation Checking
212,PRIMARY,S_SUPERB,COMPLETE,Superbias Subtraction
213,SCI,XTENSION,IMAGE,Image extension
214,SCI,BITPIX,-32,array data type
215,SCI,NAXIS,3,number of array dimensions
216,SCI,NAXIS1,160,
217,SCI,NAXIS2,160,
218,SCI,NAXIS3,2925,
219,SCI,PCOUNT,0,number of parameters
220,SCI,GCOUNT,1,number of groups
221,SCI,EXTNAME,SCI,extension name
222,SCI,MJD-BEG,59980.79313982639,[d] exposure start time in MJD
223,SCI,MJD-AVG,59980.98986482639,[d] exposure mid-point in MJD
224,SCI,MJD-END,59981.18658982639,[d] exposure end time in MJD
225,SCI,TDB-BEG,59980.79478793945,[d] TDB time of exposure start in MJD
226,SCI,TDB-MID,59980.99152055186,[d] TDB time of exposure mid-point in MJD
227,SCI,TDB-END,59981.18825315506,[d] TDB time of exposure end in MJD
228,SCI,XPOSURE,32294.376,[s] Effective exposure time
229,SCI,TELAPSE,34025.312,[s] Total elapsed exposure time
230,SCI,REFFRAME,EME2000,Ephemeris reference frame
231,SCI,EPH_TYPE,Definitive,Definitive or Predicted
232,SCI,EPH_TIME,59980.98986482639,[d] MJD time of position and velocity vectors
233,SCI,JWST_X,-109076334.2464736,[km] barycentric JWST X coordinate at MJD_AVG
234,SCI,JWST_Y,94433294.73403105,[km] barycentric JWST Y coordinate at MJD_AVG
235,SCI,JWST_Z,40686882.92015418,[km] barycentric JWST Z coordinate at MJD_AVG
236,SCI,OBSGEO-X,-580663789.590796,[m] geocentric JWST X coordinate at MJD_AVG
237,SCI,OBSGEO-Y,1473223684.96429,[m] geocentric JWST Y coordinate at MJD_AVG
238,SCI,OBSGEO-Z,354800456.4779049,[m] geocentric JWST Z coordinate at MJD_AVG
239,SCI,JWST_DX,-21.10697522235143,[km/s] barycentric JWST X velocity at MJD_AVG
240,SCI,JWST_DY,-20.12429662062409,[km/s] barycentric JWST Y velocity at MJD_AVG
241,SCI,JWST_DZ,-8.577994074587187,[km/s] barycentric JWST Z velocity at MJD_AVG
242,SCI,OBSGEODX,-161.5196697606875,[m/s] geocentric JWST X velocity at MJD_AVG
243,SCI,OBSGEODY,-159.9559942000606,[m/s] geocentric JWST Y velocity at MJD_AVG
244,SCI,OBSGEODZ,75.94138735884412,[m/s] geocentric JWST Z velocity at MJD_AVG
245,SCI,PA_APER,285.32540230903925,[deg] Position angle of aperture used
246,SCI,VA_SCALE,1.0000386769867462,Velocity aberration scale factor
247,SCI,BUNIT,MJy/sr,physical units of the array values
248,SCI,PHOTMJSR,4.473999977111816,Flux density (MJy/steradian) producing 1 cps
249,SCI,PHOTUJA2,105.15882169395023,Flux density (uJy/arcsec2) producing 1 cps
250,SCI,PIXAR_SR,2.23e-14,Nominal pixel area in steradians
251,SCI,PIXAR_A2,0.0009453,Nominal pixel area in arcsec^2
252,SCI,RADESYS,ICRS,Name of the coordinate reference frame
253,SCI,RA_V1,234.71809989889192,[deg] RA of telescope V1 axis
254,SCI,DEC_V1,50.53132712831115,[deg] Dec of telescope V1 axis
255,SCI,PA_V3,284.73446821210723,[deg] Position angle of telescope V3 axis
256,SCI,WCSAXES,2,number of World Coordinate System axes
257,SCI,CRPIX1,80.31,axis 1 coordinate of the reference pixel
258,SCI,CRPIX2,78.22,axis 2 coordinate of the reference pixel
259,SCI,CRVAL1,234.88402868566,first axis value at the reference pixel
260,SCI,CRVAL2,50.460781371758,second axis value at the reference pixel
261,SCI,CTYPE1,RA---TAN,Axis 1 type
262,SCI,CTYPE2,DEC--TAN,Axis 2 type
263,SCI,CUNIT1,deg,Axis 1 units
264,SCI,CUNIT2,deg,Axis 2 units
265,SCI,CD1_1,-2.2760461514651e-06,"linear transformation matrix element, CD matrix"
266,SCI,CD1_2,-8.2141376211297e-06,"linear transformation matrix element, CD matrix"
267,SCI,CD2_1,-8.1887964829095e-06,"linear transformation matrix element, CD matrix"
268,SCI,CD2_2,2.2507707297963e-06,"linear transformation matrix element, CD matrix"
269,SCI,S_REGION,POLYGON ICRS 234.885308603 50.461257165 234.883243861 50.461616824 234.882672078 50.460307089 234.884736286 50.459946489,spatial extent of the observation
270,SCI,V2_REF,-148.485879,[arcsec] Telescope V2 coord of reference point
271,SCI,V3_REF,-432.237215,[arcsec] Telescope V3 coord of reference point
272,SCI,VPARITY,-1,Relative sense of rotation between Ideal xy and
273,SCI,V3I_YANG,0.4629549,[deg] Angle from V3 axis to Ideal y axis
274,SCI,RA_REF,234.8840220631934,[deg] Right ascension of the reference point
275,SCI,DEC_REF,50.460781925725826,[deg] Declination of the reference point
276,SCI,ROLL_REF,284.86244740903925,[deg] V3 roll angle at the ref point (N over E)
277,SCI,VELOSYS,-11593.45,[m/s] Barycentric correction to radial velocity
278,SCI,XREF_SCI,80.31,Aperture X reference point in SCI frame
279,SCI,YREF_SCI,78.22,Aperture Y reference point in SCI frame
280,SCI,EXTVER,1,extension value
281,ERR,XTENSION,IMAGE,Image extension
282,ERR,BITPIX,-32,array data type
283,ERR,NAXIS,3,number of array dimensions
284,ERR,NAXIS1,160,
285,ERR,NAXIS2,160,
286,ERR,NAXIS3,2925,
287,ERR,PCOUNT,0,number of parameters
288,ERR,GCOUNT,1,number of groups
289,ERR,EXTNAME,ERR,extension name
290,ERR,BUNIT,MJy/sr,physical units of the array values
291,ERR,EXTVER,1,extension value
292,DQ,XTENSION,IMAGE,Image extension
293,DQ,BITPIX,32,array data type
294,DQ,NAXIS,3,number of array dimensions
295,DQ,NAXIS1,160,
296,DQ,NAXIS2,160,
297,DQ,NAXIS3,2925,
298,DQ,PCOUNT,0,number of parameters
299,DQ,GCOUNT,1,number of groups
300,DQ,BSCALE,1,
301,DQ,BZERO,2147483648,
302,DQ,EXTNAME,DQ,extension name
303,DQ,EXTVER,1,extension value
304,AREA,XTENSION,IMAGE,Image extension
305,AREA,BITPIX,-32,array data type
306,AREA,NAXIS,2,number of array dimensions
307,AREA,NAXIS1,160,
308,AREA,NAXIS2,160,
309,AREA,PCOUNT,0,number of parameters
310,AREA,GCOUNT,1,number of groups
311,AREA,EXTNAME,AREA,extension name
312,AREA,EXTVER,1,extension value
313,INT_TIMES,XTENSION,BINTABLE,binary table extension
314,INT_TIMES,BITPIX,8,array data type
315,INT_TIMES,NAXIS,2,number of array dimensions
316,INT_TIMES,NAXIS1,52,length of dimension 1
317,INT_TIMES,NAXIS2,2925,length of dimension 2
318,INT_TIMES,PCOUNT,0,number of group parameters
319,INT_TIMES,GCOUNT,1,number of groups
320,INT_TIMES,TFIELDS,7,number of table fields
321,INT_TIMES,EXTNAME,INT_TIMES,extension name
322,INT_TIMES,EXTVER,1,extension value
323,INT_TIMES,TTYPE1,integration_number,
324,INT_TIMES,TFORM1,J,
325,INT_TIMES,TTYPE2,int_start_MJD_UTC,
326,INT_TIMES,TFORM2,D,
327,INT_TIMES,TTYPE3,int_mid_MJD_UTC,
328,INT_TIMES,TFORM3,D,
329,INT_TIMES,TTYPE4,int_end_MJD_UTC,
330,INT_TIMES,TFORM4,D,
331,INT_TIMES,TTYPE5,int_start_BJD_TDB,
332,INT_TIMES,TFORM5,D,
333,INT_TIMES,TTYPE6,int_mid_BJD_TDB,
334,INT_TIMES,TFORM6,D,
335,INT_TIMES,TTYPE7,int_end_BJD_TDB,
336,INT_TIMES,TFORM7,D,
337,VAR_POISSON,XTENSION,IMAGE,Image extension